### ISSUE TITLE
Miri does not know about niches

### ISSUE THREAD

**Issue by gnzlbg** [solson/miri#633] opened 2019-02-14 01:07 UTC
This passes on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=727bafd518424eca896ab431230db227):

```rust
#![feature(rustc_attrs)]
#[rustc_layout_scalar_valid_range_start(0)]
#[rustc_layout_scalar_valid_range_end(15)]
pub struct Imm4(pub u8);

fn main() {
    let _y = unsafe { Imm4(3_u8) };
    let _z = unsafe { Imm4(22_u8) };
}
```

**Comment by RalfJung** [comment] 2019-02-14 08:06
This is a duplicate of https://github.com/solson/miri/issues/508.

If you look at the MIR, there is no moment here in which an `Imm4` is actually assigned, meaning there is no reason to assume that we even have a valid `Imm4`.

**Closed by RalfJung** 2019-02-14 08:06 UTC
